package com.systar.simulator.generator;

import java.util.Optional;
import java.util.Random;

/**
 * Context passed to each {@link DataGenerator#generate(GenerationContext)} call.
 * <p>
 * Provides time-aware state, a reproducible random source, and access to
 * values generated by peer data points within the same device, enabling
 * correlated generators.
 */
public interface GenerationContext {

    /**
     * Milliseconds elapsed since the simulation started.
     *
     * @return elapsed time in milliseconds
     */
    long elapsedMillis();

    /**
     * Retrieve the most recently generated value of a peer data point.
     *
     * @param dataPointId the identifier of the peer data point
     * @return the peer's last generated value, or {@link Optional#empty()} if unavailable
     */
    Optional<Object> getPeerValue(String dataPointId);

    /**
     * Shared random source for noise and variability.
     *
     * @return a {@link Random} instance
     */
    Random random();
}
