package com.systar.data.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Alarm message entity corresponding to the t_alarm_message table.
 * <p>
 * Records individual alarm events generated by alarm rules.
 */
@Data
@TableName("t_alarm_message")
public class AlarmMessageEntity {

    /** Alarm state constant: pending (not yet handled). */
    public static final int STATE_PENDING = 1;
    /** Alarm state constant: handled. */
    public static final int STATE_HANDLED = 2;
    /** Recovery flag: not recovered. */
    public static final int RECOVERED_NO = 0;
    /** Recovery flag: recovered. */
    public static final int RECOVERED_YES = 1;
    /** Suppressed flag: not suppressed. */
    public static final int SUPPRESSED_NO = 0;
    /** Suppressed flag: suppressed. */
    public static final int SUPPRESSED_YES = 1;
    /** Silenced flag: not silenced. */
    public static final int SILENCED_NO = 0;
    /** Silenced flag: silenced. */
    public static final int SILENCED_YES = 1;

    @TableId(type = IdType.AUTO)
    private Integer id;

    /** Reference to t_error_message_log.id. */
    @TableField("log_id")
    private Integer monitorId;

    /** Display caption of the alarm. */
    private String caption;

    /** Handle state: 1=pending, 2=handled. */
    private Integer state;

    /** Whether alarm is auto (1) or manual (2). */
    @TableField("auto")
    private Integer autoType;

    /** Alarm time (from referenced log). */
    private LocalDateTime alarmTime;

    /** Whether the alarm has been recovered. */
    private Integer recovered;

    /** Alarm severity level (reference to t_event_rank.id). */
    private Integer warnId;

    /** Correlation group ID for grouping related alarms. */
    private String correlationGroup;

    /** Root cause alarm ID (set when this alarm's root cause is confirmed). */
    private Integer rootCauseId;

    /** Whether this alarm is suppressed by a root cause confirmation. */
    private Integer suppressed;

    /** Whether this alarm was silenced during a maintenance window. */
    private Integer silenced;

    /** Escalation level: 0=original, 1=first escalation, 2=second escalation. */
    private Integer escalationLevel;

    /** Device ID for fast correlation queries (denormalized from asset tree). */
    private Integer deviceId;
}
